apiVersion: batch/v1
kind: CronJob
metadata:
  name: older-deleter
  namespace: cjarcau
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: older-deleter-cronjob
            image: scr4pp/kubernetes_cronjob
            env:
              - name: NAMESPACE
                value: cjarcau
              - name: OLDER_THEN
                value: "20"
              - name: POSTGRES_USER
                value: postgres
              - name: POSTGRES_PASS
                value: password
              - name: POSTGRES_HOST
                value: postgres
              - name: POSTGRES_PORT
                value: "32102"
              - name: POSTGRES_DB
                value: postgres
            command: ["python3", "main.py"]
          restartPolicy: OnFailure
